# -*- coding: utf-8 -*-
"""Build the explicit question-location table for the screenshot fetcher.

Scans every question-bearing PDF in both modules, records where each question
starts and ends, and writes:

    question_locations.json   the authority rm_feedback.py consults (hand-editable)
    QUESTION-LOOKUP.md         a human-readable view of the same table

Re-run after adding a new paper, or after hand-editing the JSON to regenerate
the MD view:    py -3.13 build_question_map.py
"""
import importlib.util
import io
import json
import os
import time

HERE = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location("rmf", os.path.join(HERE, "rm_feedback.py"))
m = importlib.util.module_from_spec(spec)
spec.loader.exec_module(m)

import glob
import pymupdf

MAX_Q = 30


def build():
    table = m.qmap()
    rows = []
    for module, dirs in sorted(m.QUESTION_DIRS.items()):
        for rel_dir in dirs:
            d = os.path.join(m.STUDY, rel_dir.replace("/", os.sep))
            for f in sorted(glob.glob(os.path.join(d, "*.pdf"))):
                name = os.path.basename(f)
                if not m.SRC_NAME_RE.search(name):
                    continue
                rel = os.path.relpath(f, m.STUDY).replace(os.sep, "/")
                entry = table.setdefault(module, {}).setdefault(rel, {})
                try:
                    doc = pymupdf.open(f)
                except Exception as e:
                    print("  !! %s: %s" % (name, e))
                    continue
                n_found = 0
                for q in range(1, MAX_Q + 1):
                    if str(q) in entry:          # hand edits win; never overwrite
                        n_found += 1
                        continue
                    loc = m._locate(doc, q)
                    if loc:
                        p, y0, last, end_y = loc
                        entry[str(q)] = {
                            "page": p + 1, "y0": round(y0, 1),
                            "end_page": last + 1,
                            "y1": (round(end_y, 1) if end_y is not None else None)}
                        n_found += 1
                doc.close()
                rows.append((module, rel, entry))
                print("  %-4s %-52s %2d questions" % (module, name[:52], n_found))
    m.qmap_save()

    # ---- human-readable view ----
    md = [u"# Question lookup table — where each screenshot comes from",
          u"",
          u"> Generated by `build_question_map.py` on %s. **The JSON "
          u"(`question_locations.json`) is the authority** — the watcher reads it "
          u"before any scanning. To fix a wrong location, edit the JSON (pages are "
          u"1-based, y in PDF points from the page top) and re-run the builder to "
          u"refresh this view. Entries already in the JSON are never overwritten."
          % time.strftime("%Y-%m-%d %H:%M"),
          u""]
    for module, rel, entry in rows:
        if not entry:
            continue
        md.append(u"## %s · `%s`" % (module, rel))
        md.append(u"")
        md.append(u"| Question | Starts | Ends | Grey command |")
        md.append(u"|---|---|---|---|")
        for qs in sorted(entry, key=int):
            e = entry[qs]
            start = u"p.%d @ y=%.0f" % (e["page"], e["y0"])
            if e.get("y1") is not None:
                end = u"p.%d @ y=%.0f" % (e["end_page"], e["y1"])
            else:
                end = u"p.%d (bottom)" % e["end_page"]
            hint = os.path.basename(rel).split(".")[0]
            md.append(u"| Q%s | %s | %s | `screenshot q%s %s` |"
                      % (qs, start, end, qs,
                         "" if "example" in hint else hint[:24]))
        md.append(u"")
    out = os.path.join(HERE, "QUESTION-LOOKUP.md")
    with io.open(out, "w", encoding="utf-8") as fh:
        fh.write(u"\n".join(md))
    print("\nwrote %s and %s" % (os.path.basename(m.QMAP_PATH), os.path.basename(out)))


if __name__ == "__main__":
    build()
